### ISSUE TITLE
Node Request: Dataset Caption Visualisers--"Word Cloud" and "Network Graph" Nodes

### ISSUE THREAD

**Issue by rafstahelin** [daxcay/ComfyUI-JDCN#10]
These nodes are basic tools for visualising the concepts in a dataset of paired images and caption files

The Word Cloud preview image, gives an intuitive way of seeing what is in the dataset. Words with biggest frequency appear in larger fonts. Network Graph similarly shows a node based frequency visualisation. Both visualisers are python libraries that can easily built into a comfyui workflow

### Input:
path to directory--AnyfileList Node
### Output:
Image

Examples:
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/64715158/2a5d50ff-0602-4212-ad5c-22e25756c968)
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/64715158/48ec04d0-405c-4c46-b356-c5fa5e6c7ca8)

Optional Frequency Table:
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/64715158/39e07751-f9d3-44c6-964e-d377122f8ee5)

An example of repo that uses these visualisers:
[https://github.com/jiayev/GPT4V-Image-Captioner](url)
Here's how it looks on their webapp:
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/64715158/39142681-fd6e-4950-b22e-f9e03c9285ea)

**Comment by daxcay** [comment]
Node Made

https://github.com/daxcay/ComfyUI-JDCN/commit/596b5d1c110c0cc96dcb7c3dd80678e94766fd30
