### ISSUE TITLE
Make BatchImageLoadFromDir

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#11]
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/152957217/9e84911b-9f53-4a3a-bf8b-1b66572c56d8)
Similar to this make for Images

**Comment by daxcay** [comment]
https://github.com/daxcay/ComfyUI-JDCN/commit/bd2c525bb1071872cd3641a066d876ebdc2cbfd0

Node Request Fulfilled!
