### ISSUE TITLE
Random Prompt From Multiline Type Box

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#12]
Box Input:

1) Index - Selected line from Type Box
2) Select Line Count  - Number of lines selected (Eg: 1,2,3) at a time 
3) Index Selection - Fixed, Increment, Decrement, Random
4) Selection Order - TopToBottom, BottomToTop, Random
5) Separator - Line Separated by (Comma, space, next line, keyword)
6) Separator Keyword - [Optional] typebox for finding the specific keyword 
7) TYPE BOX - Multiline Type Box of lines 

Output: 

1) Index - Selected Index
2) Line Count - Number of lines Selected 
3) String - Output lines

**Comment by jerrydavos** [comment]
Update 
*  5) Separator - Line Separated by (Comma, space, next line) 
*  6) Separator Keyword - [Optional] typebox for finding the specific keyword

**Comment by daxcay** [comment]
New Node added
