### ISSUE TITLE
The Pathlist of the JDCN_AnyFileSelectora node could not be converted to input, which was still possible a few days ago. The node in the converted old workflow reported an error  JDCN_AnyFileSelectora节点的Pathlist无法转换为input，几天前是还是可以的，转换过的老的工作流中的该节点报错

### ISSUE THREAD

**Issue by kenic123** [daxcay/ComfyUI-JDCN#18]
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/67681738/02c481bf-caa7-4ef6-b672-e1d4a3083e00)
JDCN_AnyFileSelectora节点的Pathlist无法转换为input，几天前是还是可以的，转换过的老的工作流中的该节点报错
The Pathlist of the JDCN_AnyFileSelectora node could not be converted to input, which was still possible a few days ago. The node in the converted old workflow reported an error

**Comment by kenic123** [comment]
I can't figure out why, when the same package is tested in two different comfyui's, it actually comes up with two different interfaces

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/67681738/d42de91d-c0a0-4197-9d36-d353fe32a946)

**Comment by kenic123** [comment]
但是右键菜单中这个PathList是不能被转换的

**Comment by daxcay** [comment]
Hi, I have not updated this node recently. please try again with a fresh install.

**Comment by jerrydavos** [comment]
The Custom Comfyui Theme that you have installed is probably causing this issue.

**Comment by timurius** [comment]
I have the same issue and can\`t figure out any solution. I`m using ComfyUI without any themes installed.

**Comment by jerrydavos** [comment]
Anyone having this problem, Update JDCN nodes, Reload Browser and Recreate the node 

Right Click on the Node > Convert widget into input > Convert List into input 

![image](https://github.com/user-attachments/assets/0469e68e-d52e-424d-bcc6-d1c0fc0f1b7f)
