### ISSUE TITLE
[Concept] Save Image Custom Node

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#2]
### Title - "JDCN Image Save" - jdcnsaveimage
 

**Inputs**

- Images (Single/Batch/List)

**Node Attributes**
- Output Path
- File Name Prefix
[Optional] - Overwrite Button (True/False) - When True - Automatic Numbering will be Disabled

Automatic Numbering and Padding of 4 (Example_0001.png)

**Comment by daxcay** [comment]
Ok will work on it
