### ISSUE TITLE
Hello great developers, looking for some help

### ISSUE THREAD

**Issue by QingLuanWithoutHeart** [daxcay/ComfyUI-JDCN#21]
I want to write a code similar to your node, but I don't know how to implement it. For example, your AnyFileSelector node, but what I want is Any text Selector, which is to provide a string of text and randomly select a word from it. How can I do it?
Or can this function be implemented in this plugin?

**Comment by daxcay** [comment]
JDCN_StringManipulator search this node and see if this solves your text selection

**Comment by daxcay** [comment]
![image](https://github.com/user-attachments/assets/854505f4-589b-476a-a999-ac2c29b08817)

**Comment by QingLuanWithoutHeart** [comment]
Thank you very much, this node solved my big problem, thank you
