### ISSUE TITLE
[Update] AnyFile Selector Node

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#3]
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/152957217/3766dcb3-f665-49f5-9c51-9c0460260f69)

Add Select Index Property: Increment, Decrement or Fixed.

**Comment by daxcay** [comment]
https://github.com/daxcay/ComfyUI-JDCN/commit/560c285b50e1f6470038d68a9361ec46aae67d55

Its done.
