### ISSUE TITLE
Random seed for Batch Image/Latent load

### ISSUE THREAD

**Issue by Cloudwalker2k3** [daxcay/ComfyUI-JDCN#5]
Can you have it so that each time you generate, it randomly picks another set from the requested folder?
And a seed so we can lock that combination in place?

**Comment by daxcay** [comment]
Ok,
I'll see what i can do !

**Comment by daxcay** [comment]
Hi,

As requested i have made new nodes; please update the plugin.

Now to use like you have requested, Do this:

**For Latents:**

Use ``` JDCN_BatchLatentLoadFromList ```

Convert batch_size to input like this

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/7f0fe005-c34e-441d-9eda-a5822412333b)

And connect it with total like this

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/20024922-d68b-4f70-a511-faad0bb1a29a)

Use this to control the behavior

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/c6db7e16-a1fe-4942-bf8a-ecab244cbd73)


**For Images**

Use ``` JDCN_BatchImageLoadFromList ``` Same as above

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/164315771/7a066a60-1678-414d-979a-f98c7389617c)

To know further or you have any question you can contact me on: https://discord.gg/aGQmh62T

**Comment by daxcay** [comment]
**Closed due to Inactivity by @Cloudwalker2k3.**
