### ISSUE TITLE
Auto Batch Counter  

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#6]
Input 

Seed = 0
Range = 50 

Output 

Scene 1
Lap = Seed = 0
Range = 50 
Skip Frame = 0

Scene 2 
Lap = 1
Range = 50
Skip Frame = 50

Scene 3 
Lap = 2
Range = 50
Skip Frame = 100 

Formula (((b/b)*a)*b)

a = Lap
b= Range

Node Include
Seed Properties : 
DIsplay Skip

[AutoBatch Counter.json](https://github.com/daxcay/ComfyUI-JDCN/files/15057955/AutoBatch.Counter.json)

**Comment by daxcay** [comment]
Node request is **completed**. Update JDCN.
