### ISSUE TITLE
SafeTensor File Filter in AnyFileList

### ISSUE THREAD

**Issue by jerrydavos** [daxcay/ComfyUI-JDCN#8]
![image](https://github.com/daxcay/ComfyUI-JDCN/assets/152957217/c2f0386c-7eec-41c2-b9c9-3693da400cce)

Which can be used here

**Comment by daxcay** [comment]
Ok

**Comment by daxcay** [comment]
Will make new node !

**Comment by daxcay** [comment]
Made an update in anyfile selector node to select safe tensors and made a new node load checkpoint from anywhere.
