### ISSUE TITLE
Node Request: Search Captions and replace tag

### ISSUE THREAD

**Issue by rafstahelin** [daxcay/ComfyUI-JDCN#9]
Would love a simple node which Searches and Replaces a tag(s) from a path of text files

Input:
path to directory--AnyfileList Node
Input2:
Widget--tag(s) to be searched, ie "a photo of"
Input3:
Widget--tag(s) to be replaced with, ie "a photograph of"
Output:
Replace tags in path for all instances of searched tag(s)

Note: 
To remove tag, instead of replacing, leave Input3 widget empty

This is again very useful for model trainers. We already have the concept insertion node JCDN_TagManipulatorByImageNames.
Tag replacement is the other big use case for editing caption batches. A one node solution would streamline the process greatly

![image](https://github.com/daxcay/ComfyUI-JDCN/assets/64715158/ad11f270-af03-4033-8323-29a4c86cf6eb)

**Comment by daxcay** [comment]
Its been made in https://github.com/daxcay/ComfyUI-DRMN

**Comment by rafstahelin** [comment]
Awesome 
 🫡👊
